name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Docker Environment
        run: |
          echo "Docker version:"
          docker --version
          echo "Listing Docker containers:"
          docker ps -a
      
      - name: Build the site in the jekyll/builder container
        run: |
          export JEKYLL_VERSION=3.8
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          -e PAGES_REPO_NWO=${{ github.repository }} \
          jekyll/builder:$JEKYLL_VERSION /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future 2>&1 | tee build.log || { echo 'Jekyll build failed'; cat build.log; exit 1; }"
      
      - name: Capture build logs
        if: failure()
        run: |
          echo "Capturing logs for debugging"
          cat build.log || echo "No logs found"

      - name: Check Build Output
        run: |
          echo "Build output:"
          ls -al _site
